// server.ts – lightweight internal Pumble add‑on that exposes /file/makePublic
// ──────────────────────────────────────────────────────────────────────────────
// 1) Expects a .env with
//    PUMBLE_API_KEY   – API key generated by /api-keys generate
//    PORT             – optional, defaults to 8080
// 2) POST { "fileId": "<id_from_listMessages>" } → { "publicPath": "https://files.pumble.com/public/..." }
// 3) Deploy: `vercel deploy --prod`  or  `npm start` on Heroku/Fly/Self‑host
// 4) n8n HTTP Request node then calls this endpoint, takes publicPath and downloads the file without auth
// -----------------------------------------------------------------------------
import express, { Request, Response } from "express";
import axios from "axios";
import * as dotenv from "dotenv";

dotenv.config();

// ─── Environment sanity check ────────────────────────────────────────────────
const API_KEY = process.env.PUMBLE_API_KEY;
if (!API_KEY) {
  throw new Error("⚠️  Missing PUMBLE_API_KEY in environment variables");
}

const PORT = process.env.PORT || 8080;
const PUMBLE_BASE = "https://pumble-api-keys.addons.marketplace.cake.com";

// ─── Express setup ───────────────────────────────────────────────────────────
const app = express();
app.use(express.json());

// Health‑check for cheap uptime‑robots
app.get("/health", (_, res) => res.send("OK"));

// POST /file/makePublic { fileId }
app.post("/file/makePublic", async (req: Request, res: Response) => {
  const { fileId } = req.body as { fileId?: string };
  if (!fileId) return res.status(400).json({ error: "fileId required" });

  try {
    const { data } = await axios.post(
      `${PUMBLE_BASE}/makeFilePublic`,
      { fileId },
      { headers: { "Api-Key": API_KEY } }
    );

    if (!data?.publicPath) {
      return res.status(502).json({ error: "no publicPath returned", raw: data });
    }

    return res.json({ publicPath: data.publicPath });
  } catch (err: any) {
    console.error("makeFilePublic failed", err.response?.data || err.message);
    return res.status(500).json({ error: "makeFilePublic failed", details: err.response?.data || err.message });
  }
});

app.listen(PORT, () => console.log(`🚀 Pumble makePublic add‑on listening on :${PORT}`));

// ─── Vercel config (if deployed there) ───────────────────────────────────────
// Place next to this file as "vercel.json":
// {
//   "version": 2,
//   "builds": [ { "src": "pumble-make-public.ts", "use": "@vercel/node" } ],
//   "routes": [ { "src": "/(.*)", "dest": "/pumble-make-public.ts" } ]
// }
